package consts

var (
	defaultContentType = []byte("text/plain; charset=utf-8")
)

var (
	StrSlash                    = []byte("/")
	StrSlashSlash               = []byte("//")
	StrSlashDotDot              = []byte("/..")
	StrSlashDotSlash            = []byte("/./")
	StrSlashDotDotSlash         = []byte("/../")
	StrBackSlashDotDot          = []byte(`\..`)
	StrBackSlashDotBackSlash    = []byte(`\.\`)
	StrSlashDotDotBackSlash     = []byte(`/..\`)
	StrBackSlashDotDotBackSlash = []byte(`\..\`)
	StrCRLF                     = []byte("\r\n")
	StrHTTP                     = []byte("http")
	StrHTTPS                    = []byte("https")
	StrHTTP11                   = []byte("HTTP/1.1")
	StrColon                    = []byte(":")
	StrColonSlashSlash          = []byte("://")
	StrColonSpace               = []byte(": ")
	StrCommaSpace               = []byte(", ")
	StrGMT                      = []byte("GMT")

	StrResponseContinue   = []byte("HTTP/1.1 100 Continue\r\n\r\n")
	StrExpect             = []byte(HeaderExpect)
	StrConnection         = []byte(HeaderConnection)
	StrContentLength      = []byte(HeaderContentLength)
	StrContentType        = []byte(HeaderContentType)
	StrDate               = []byte(HeaderDate)
	StrHost               = []byte(HeaderHost)
	StrReferer            = []byte(HeaderReferer)
	StrServer             = []byte(HeaderServer)
	StrTransferEncoding   = []byte(HeaderTransferEncoding)
	StrContentEncoding    = []byte(HeaderContentEncoding)
	StrAcceptEncoding     = []byte(HeaderAcceptEncoding)
	StrUserAgent          = []byte(HeaderUserAgent)
	StrCookie             = []byte(HeaderCookie)
	StrSetCookie          = []byte(HeaderSetCookie)
	StrLocation           = []byte(HeaderLocation)
	StrIfModifiedSince    = []byte(HeaderIfModifiedSince)
	StrLastModified       = []byte(HeaderLastModified)
	StrAcceptRanges       = []byte(HeaderAcceptRanges)
	StrRange              = []byte(HeaderRange)
	StrContentRange       = []byte(HeaderContentRange)
	StrAuthorization      = []byte(HeaderAuthorization)
	StrTE                 = []byte(HeaderTE)
	StrTrailer            = []byte(HeaderTrailer)
	StrMaxForwards        = []byte(HeaderMaxForwards)
	StrProxyConnection    = []byte(HeaderProxyConnection)
	StrProxyAuthenticate  = []byte(HeaderProxyAuthenticate)
	StrProxyAuthorization = []byte(HeaderProxyAuthorization)
	StrWWWAuthenticate    = []byte(HeaderWWWAuthenticate)
	StrVary               = []byte(HeaderVary)

	StrCookieExpires        = []byte("expires")
	StrCookieDomain         = []byte("domain")
	StrCookiePath           = []byte("path")
	StrCookieHTTPOnly       = []byte("HttpOnly")
	StrCookieSecure         = []byte("secure")
	StrCookiePartitioned    = []byte("Partitioned")
	StrCookieMaxAge         = []byte("max-age")
	StrCookieSameSite       = []byte("SameSite")
	StrCookieSameSiteLax    = []byte("Lax")
	StrCookieSameSiteStrict = []byte("Strict")
	StrCookieSameSiteNone   = []byte("None")

	StrClose               = []byte("close")
	StrGzip                = []byte("gzip")
	StrBr                  = []byte("br")
	StrZstd                = []byte("zstd")
	StrDeflate             = []byte("deflate")
	StrKeepAlive           = []byte("keep-alive")
	StrUpgrade             = []byte("Upgrade")
	StrChunked             = []byte("chunked")
	StrIdentity            = []byte("identity")
	Str100Continue         = []byte("100-continue")
	StrPostArgsContentType = []byte("application/x-www-form-urlencoded")
	StrDefaultContentType  = []byte("application/octet-stream")
	StrMultipartFormData   = []byte("multipart/form-data")
	StrBoundary            = []byte("boundary")
	StrBytes               = []byte("bytes")
	StrBasicSpace          = []byte("Basic ")

	StrApplicationSlash = []byte("application/")
	StrImageSVG         = []byte("image/svg")
	StrImageIcon        = []byte("image/x-icon")
	StrFontSlash        = []byte("font/")
	StrMultipartSlash   = []byte("multipart/")
	StrTextSlash        = []byte("text/")
)
